---
# tasks file for ansible-hashi-vault

- include_tasks: set_facts.yml
  tags:
    - hashi_vault_health_status
    - hashi_vault_init
    - hashi_vault_key_status
    - hashi_vault_leader
    - hashi_vault_list_policies
    - hashi_vault_mounts
    - hashi_vault_policies
    - hashi_vault_read_policies
    - hashi_vault_reinit
    - hashi_vault_seal
    - hashi_vault_unseal

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: account.yml
  tags:
    - hashi_vault_account

- include_tasks: install.yml
  tags:
    - hashi_vault_install

- include_tasks: config.yml
  tags:
    - hashi_vault_config

- include_tasks: service.yml
  tags:
    - hashi_vault_service

- include_tasks: init.yml
  tags:
    - hashi_vault_init
    - hashi_vault_reinit

- include_tasks: key_status.yml
  tags:
    - hashi_vault_key_status
  when: hashi_vault_show_key_status

- include_tasks: secrets.yml
  when: hashi_vault_manage_secrets

- include_tasks: health.yml
  tags:
    - hashi_vault_health_status
  when: hashi_vault_show_health_status

- include_tasks: leader.yml
  tags:
    - hashi_vault_leader
  when: hashi_vault_show_leader

- include_tasks: mounts.yml
  tags:
    - hashi_vault_mounts
  when: hashi_vault_show_mounts

- include_tasks: policies.yml
  tags:
    - hashi_vault_policies
  when: not ansible_check_mode
